name: med_chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - flask
      - python-dotenv
      - joblib
      - Pillow
      - markdown
      - langchain==0.2.12
      - langchain-core==0.2.27
      - langchain-community==0.2.12
      - langchain-google-genai==1.0.3
      - google-generativeai==0.7.2
      - pinecone-client
      - pinecone-text
